//Nome: Rafael Tomé da Silva - RA:2623412;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rafae
 */
public class FormCadastrarMoletom extends javax.swing.JFrame {
    
    private Moletom moletom;
    private Estoque estoque = new Estoque();

    private static FormCadastrarMoletom cadMolUnico;
    
    public FormCadastrarMoletom() {
        initComponents();
        listarTab();
    }
    
    // MÉTODO SINGLETON
    public static FormCadastrarMoletom getCadastrarMoletom(){
        if(cadMolUnico == null){
        cadMolUnico = new FormCadastrarMoletom();
        }
        return cadMolUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ctCapuz = new javax.swing.JTextField();
        lbEstampa = new javax.swing.JLabel();
        ctEstampa = new javax.swing.JTextField();
        lbMaterial = new javax.swing.JLabel();
        lbTamanho = new javax.swing.JLabel();
        ctMaterial = new javax.swing.JTextField();
        ctTamanho = new javax.swing.JTextField();
        lbCuidados = new javax.swing.JLabel();
        lbCor = new javax.swing.JLabel();
        ctCuidados = new javax.swing.JTextField();
        ctCor = new javax.swing.JTextField();
        lbMarca = new javax.swing.JLabel();
        ctMarca = new javax.swing.JTextField();
        lbCapuz = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        btLimpar1 = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        tblCamisa = new javax.swing.JScrollPane();
        tbMoletom = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        ctCapuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctCapuzActionPerformed(evt);
            }
        });

        lbEstampa.setText("Informe a estampa (LOGO DA MARCA, LISA, DESENHO):");

        lbMaterial.setText("Informe o tipo de material (ALGODAO, JEANS):");

        lbTamanho.setText("Informe o tamanho (PP, P, M, G, GG):");

        ctTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctTamanhoActionPerformed(evt);
            }
        });

        lbCuidados.setText("Informe os cuidados do material (lavar a mao, lavar na maquina):");

        lbCor.setText("Informe a cor (branca, preta, azul):");

        ctCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctCorActionPerformed(evt);
            }
        });

        lbMarca.setText("Informe a marca (BAW, SUFGANG, APPROVE, WATS, HIGH):");

        ctMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctMarcaActionPerformed(evt);
            }
        });

        lbCapuz.setText("Informe o tipo de capuz (COM CAPUZ , SEM CAPUZ):");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar1.setText("Limpar");
        btLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpar1ActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        tbMoletom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tamanho", "Cor", "Marca", "Capuz", "Estampa", "Material", "Cuidados"
            }
        ));
        tblCamisa.setViewportView(tbMoletom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCor, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctCor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ctMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbCuidados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ctMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctCuidados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbCapuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbEstampa, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ctEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(ctCapuz, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 170, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btRemover)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar1)
                        .addGap(18, 18, 18)
                        .addComponent(btSair)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tblCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTamanho)
                    .addComponent(ctTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCor)
                    .addComponent(ctCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMarca)
                    .addComponent(ctMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCapuz)
                    .addComponent(ctCapuz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstampa)
                    .addComponent(ctEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaterial)
                    .addComponent(ctMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCuidados)
                    .addComponent(ctCuidados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btLimpar1)
                    .addComponent(btCadastrar)
                    .addComponent(btConsultar)
                    .addComponent(btAlterar)
                    .addComponent(btRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(tblCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctTamanhoActionPerformed

    private void ctCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctCorActionPerformed

    private void ctMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctMarcaActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpar1ActionPerformed
        limpar();
    }//GEN-LAST:event_btLimpar1ActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadastrarMoletom();
        listarTab();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultarMoletom();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterarMoletom();
        listarTab();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        remover();
        listarTab();
    }//GEN-LAST:event_btRemoverActionPerformed

    private void ctCapuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctCapuzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctCapuzActionPerformed

    public void listarTab(){
        DefaultTableModel modelo = (DefaultTableModel) tbMoletom.getModel();
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Moletom moletom : estoque.getBdMoletom()){
            modelo.insertRow(posLin, new Object []{moletom.getTamanho(),
                                                   moletom.getCor(),
                                                   moletom.getMarca(),
                                                   moletom.getCapuz(),
                                                   moletom.getEstampa(), 
                                                   moletom.getMaterial().getTipo(), 
                                                   moletom.getMaterial().getCuidados()});
            posLin++;
        }
    }
    
    public void remover(){
    Moletom moletomConsulta = new Moletom();
    
    // Definindo os atributos da camisa com base nos campos de texto
    try {
        moletomConsulta.setTamanho(ctTamanho.getText());
    } catch (TamanhoErradoException tee) {
        tee.impTamanhoErrado();
        return;
    }
    
    try {
        moletomConsulta.setCor(ctCor.getText());
    } catch (CorErradaException cee) {
        cee.impCorErrada();
        return;
    }
    
    try {
        moletomConsulta.setMarca(ctMarca.getText());
    } catch (MarcaErradaException mee) {
        mee.impMarcaErrada();
        return;
    }
    
    try {
        moletomConsulta.setCapuz(ctCapuz.getText());
    } catch (CapuzErradoException mee) {
        mee.impCapuzErrado();
        return;
    }
    
    try {
        moletomConsulta.setEstampa(ctEstampa.getText());
    } catch (EstampaErradaException eee) {
        eee.impEstampaErrada();
        return;
    }
    
    try {
        moletomConsulta.getMaterial().setTipo(ctMaterial.getText());
    } catch (TipoErradoException tee) {
        tee.impTipoErrado();
        return;
    }
    
    try {
        moletomConsulta.getMaterial().setCuidados(ctCuidados.getText());
    } catch(CuidadosErradosException cee) {
        cee.impCuidadosErrados();
        return;
    }
    
    
    
    
    
    
    if (moletomConsulta != null) {
        ctTamanho.setText(moletomConsulta.getTamanho());
        ctCor.setText(moletomConsulta.getCor());
        ctMarca.setText(moletomConsulta.getMarca());
        ctCapuz.setText(moletomConsulta.getCapuz());
        ctEstampa.setText(moletomConsulta.getEstampa());
        int x = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esse Moletom?", "Confirmacao de exclusao",JOptionPane.YES_NO_CANCEL_OPTION);
        if(x == 0){
            estoque.removeMoletom(moletomConsulta);
            JOptionPane.showMessageDialog(null, "Moletom excluida com sucesso", "Exclusao de Moletom", 1);
        limpar();
        }
    } else {
        JOptionPane.showMessageDialog(null, "Nao existe moletom com esses dados", "", JOptionPane.YES_NO_CANCEL_OPTION);
        limpar();
    }
}
    
    public void alterarMoletom(){
    Moletom moletomConsulta = new Moletom();
    
    // Definindo os atributos da camisa com base nos campos de texto
        
    try {
        moletomConsulta.setTamanho(ctTamanho.getText());
    } catch (TamanhoErradoException tee) {
        tee.impTamanhoErrado();
        return;
    }
    
    try {
        moletomConsulta.setCor(ctCor.getText());
    } catch (CorErradaException cee) {
        cee.impCorErrada();
        return;
    }
    
    try {
        moletomConsulta.setMarca(ctMarca.getText());
    } catch (MarcaErradaException mee) {
        mee.impMarcaErrada();
        return;
    }
    
    try {
        moletomConsulta.setCapuz(ctCapuz.getText());
    } catch (CapuzErradoException mee) {
        mee.impCapuzErrado();
        return;
    }
    
    try {
        moletomConsulta.setEstampa(ctEstampa.getText());
    } catch (EstampaErradaException eee) {
        eee.impEstampaErrada();
        return;
    }
    
    try {
        moletomConsulta.getMaterial().setTipo(ctMaterial.getText());
    } catch (TipoErradoException tee) {
        tee.impTipoErrado();
        return;
    }
    
    try {
        moletomConsulta.getMaterial().setCuidados(ctCuidados.getText());
    } catch(CuidadosErradosException cee) {
        cee.impCuidadosErrados();
        return;
    }
    
    
    
    Moletom moletomAtualizada = estoque.atualizaMoletom(moletomConsulta);
    
    
    if (moletomAtualizada != null) {
        ctTamanho.setText(moletomAtualizada.getTamanho());
        ctCor.setText(moletomAtualizada.getCor());
        ctMarca.setText(moletomAtualizada.getMarca());
        ctCapuz.setText(moletomAtualizada.getCapuz());
        ctEstampa.setText(moletomAtualizada.getEstampa());
        JOptionPane.showMessageDialog(null, "Dados da Moletom atualizados com sucesso!", "Atulização da Moletom",1);
    } else {
        JOptionPane.showMessageDialog(null, "Nao existe Moletom com esses dados", "Moletom inexistente", JOptionPane.ERROR_MESSAGE);
        
    }
}
    
    public void consultarMoletom() {
    Moletom moletomConsulta = new Moletom();
    
    // Definindo os atributos da camisa com base nos campos de texto
    try {
        moletomConsulta.setTamanho(ctTamanho.getText());
    } catch (TamanhoErradoException tee) {
        tee.impTamanhoErrado();
        return;
    }
    
    try {
        moletomConsulta.setCor(ctCor.getText());
    } catch (CorErradaException cee) {
        cee.impCorErrada();
        return;
    }
    
    try {
        moletomConsulta.setMarca(ctMarca.getText());
    } catch (MarcaErradaException mee) {
        mee.impMarcaErrada();
        return;
    }
    
    try {
        moletomConsulta.setCapuz(ctCapuz.getText());
    } catch (CapuzErradoException mee) {
        mee.impCapuzErrado();
        return;
    }
    
    try {
        moletomConsulta.setEstampa(ctEstampa.getText());
    } catch (EstampaErradaException eee) {
        eee.impEstampaErrada();
        return;
    }
    
    try {
        moletomConsulta.getMaterial().setTipo(ctMaterial.getText());
    } catch (TipoErradoException tee) {
        tee.impTipoErrado();
        return;
    }
    
    try {
        moletomConsulta.getMaterial().setCuidados(ctCuidados.getText());
    } catch(CuidadosErradosException cee) {
        cee.impCuidadosErrados();
        return;
    }
    
    
    moletomConsulta = estoque.consMoletom(moletomConsulta);
    
    
    if (moletomConsulta != null) {
        ctTamanho.setText(moletomConsulta.getTamanho());
        ctCor.setText(moletomConsulta.getCor());
        ctMarca.setText(moletomConsulta.getMarca());
        ctCapuz.setText(moletomConsulta.getCapuz());
        ctEstampa.setText(moletomConsulta.getEstampa());
        JOptionPane.showMessageDialog(null, "Confirme os dados da Moletom", "Confirmacao de dados",1);
    } else {
        JOptionPane.showMessageDialog(null, "Nao existe Moletom com esses dados", "Moletom inexistente", JOptionPane.ERROR_MESSAGE);
        limpar();
    }
}
    
    public void cadastrarMoletom(){
        moletom = new Moletom();
        
        try{
        try{
        moletom.setTamanho(ctTamanho.getText());
        }catch(TamanhoErradoException tee){
            tee.impTamanhoErrado();
            ctTamanho.setText("");
            ctTamanho.requestFocus();
            return;
        }
        
        try{
        moletom.setCor(ctCor.getText());
        }catch(CorErradaException cee){
            cee.impCorErrada();
            ctCor.setText("");
            ctCor.requestFocus();
            return;
        }
        
        try{        
        moletom.setMarca(ctMarca.getText());
        }catch(MarcaErradaException mee){
            mee.impMarcaErrada();
            ctMarca.setText("");
            ctMarca.requestFocus();
            return;
        }
        
        try{            
        moletom.setCapuz(ctCapuz.getText());
        }catch(CapuzErradoException mee){
            mee.impCapuzErrado();
            ctCapuz.setText("");
            ctCapuz.requestFocus();
            return;
        }
        
        try{
        moletom.setEstampa(ctEstampa.getText());
        }catch(EstampaErradaException eee){
            eee.impEstampaErrada();
            ctEstampa.setText("");
            ctEstampa.requestFocus();
            return;
        }
        try{
        moletom.getMaterial().setTipo(ctMaterial.getText());
        } catch(TipoErradoException tee){
            tee.impTipoErrado();
            ctMaterial.setText("");
            ctMaterial.requestFocus();
            return;
        }
        try{    
        moletom.getMaterial().setCuidados(ctCuidados.getText());
        }catch(CuidadosErradosException cee){
            cee.impCuidadosErrados();
            ctCuidados.setText("");
            ctCuidados.requestFocus();
            return;
        }
        moletom = estoque.cadMoletom(moletom);
        if(moletom != null){
            JOptionPane.showMessageDialog(null,"Moletom cadastrada com sucesso!", "Cadastro OK", 1);
            limpar();
        }

        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro ao cadastrar a moletom!", "Cadastro ERRO", 0);
        }
    }
    
    public void limpar(){
        ctTamanho.setText("");
        ctCor.setText("");
        ctMarca.setText("");
        ctCapuz.setText("");
        ctEstampa.setText("");
        ctMaterial.setText("");
        ctCuidados.setText("");
        ctTamanho.requestFocus();  
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja Fechar o cadastro de Moletom?", "Saida", JOptionPane.YES_NO_OPTION);
            if(resp == 0){
                this.dispose();
            }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarMoletom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarMoletom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarMoletom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarMoletom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastrarMoletom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar1;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField ctCapuz;
    private javax.swing.JTextField ctCor;
    private javax.swing.JTextField ctCuidados;
    private javax.swing.JTextField ctEstampa;
    private javax.swing.JTextField ctMarca;
    private javax.swing.JTextField ctMaterial;
    private javax.swing.JTextField ctTamanho;
    private javax.swing.JLabel lbCapuz;
    private javax.swing.JLabel lbCor;
    private javax.swing.JLabel lbCuidados;
    private javax.swing.JLabel lbEstampa;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbMaterial;
    private javax.swing.JLabel lbTamanho;
    private javax.swing.JTable tbMoletom;
    private javax.swing.JScrollPane tblCamisa;
    // End of variables declaration//GEN-END:variables
}
