//IDE 23
//Nome: Rafael Tomé da Silva - RA:2623412;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rafae
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form aaaaaaaaaaaaaaaa
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        mnBarPrinc = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        itMnCadCam = new javax.swing.JMenuItem();
        itMnCadCal = new javax.swing.JMenuItem();
        itMnCadMol = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();
        itMnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo.setText("Sistema de Gestao de Roupas");

        mnCadastro.setText("Cadastro");

        itMnCadCam.setText("Abrir Cadastro de Camisa");
        itMnCadCam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadCamActionPerformed(evt);
            }
        });
        mnCadastro.add(itMnCadCam);

        itMnCadCal.setText("Abrir Cadastro de Calca");
        itMnCadCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadCalActionPerformed(evt);
            }
        });
        mnCadastro.add(itMnCadCal);

        itMnCadMol.setText("Abrir Cadastro de Moletom");
        itMnCadMol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadMolActionPerformed(evt);
            }
        });
        mnCadastro.add(itMnCadMol);

        mnBarPrinc.add(mnCadastro);

        mnSair.setText("Sair");

        itMnSair.setText("Fechar");
        itMnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnSairActionPerformed(evt);
            }
        });
        mnSair.add(itMnSair);

        mnBarPrinc.add(mnSair);

        setJMenuBar(mnBarPrinc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Titulo)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(133, 133, 133))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMnCadCamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadCamActionPerformed
        FormCadastrarCamisa.getCadastrarCamisa().setVisible(true);
    }//GEN-LAST:event_itMnCadCamActionPerformed

    private void itMnCadCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadCalActionPerformed
        FormCadastrarCalca.getCadastrarCalca().setVisible(true);
    }//GEN-LAST:event_itMnCadCalActionPerformed

    private void itMnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnSairActionPerformed
        sair();
    }//GEN-LAST:event_itMnSairActionPerformed

    private void itMnCadMolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadMolActionPerformed
        FormCadastrarMoletom.getCadastrarMoletom().setVisible(true);
    }//GEN-LAST:event_itMnCadMolActionPerformed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja Sair da Aplicacao?", "Saida", JOptionPane.YES_NO_OPTION);
            if(resp == 0){
                this.dispose();
            }
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JMenuItem itMnCadCal;
    private javax.swing.JMenuItem itMnCadCam;
    private javax.swing.JMenuItem itMnCadMol;
    private javax.swing.JMenuItem itMnSair;
    private javax.swing.JMenuBar mnBarPrinc;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnSair;
    // End of variables declaration//GEN-END:variables
}
