//Nome: Rafael Tomé da Silva - RA:2623412;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rafae
 */
public class FormCadastrarCamisa extends javax.swing.JFrame {
    
    private Camisa camisa;
    private Estoque estoque = new Estoque();
    
    private static FormCadastrarCamisa cadCamUnico;
    
    public FormCadastrarCamisa() {
        initComponents();
        listarTab();
    }
    
    // MÉTODO SINGLETON
    public static FormCadastrarCamisa getCadastrarCamisa(){
        if(cadCamUnico == null){
        cadCamUnico = new FormCadastrarCamisa();
        }
        return cadCamUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTamanho = new javax.swing.JLabel();
        ctTamanho = new javax.swing.JTextField();
        lbCor = new javax.swing.JLabel();
        ctCor = new javax.swing.JTextField();
        lbMarca = new javax.swing.JLabel();
        ctMarca = new javax.swing.JTextField();
        lbManga = new javax.swing.JLabel();
        ctManga = new javax.swing.JTextField();
        lbEstampa = new javax.swing.JLabel();
        ctEstampa = new javax.swing.JTextField();
        lbMaterial = new javax.swing.JLabel();
        ctMaterial = new javax.swing.JTextField();
        lbCuidados = new javax.swing.JLabel();
        ctCuidados = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        tblCamisa = new javax.swing.JScrollPane();
        tbCamisa = new javax.swing.JTable();
        btAlterar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Camisa");
        setAlwaysOnTop(true);

        lbTamanho.setText("Informe o tamanho (PP, P, M, G, GG):");

        ctTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctTamanhoActionPerformed(evt);
            }
        });

        lbCor.setText("Informe a cor (branca, preta, azul):");

        ctCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctCorActionPerformed(evt);
            }
        });

        lbMarca.setText("Informe a marca (BAW, SUFGANG, APPROVE, WATS, HIGH):");

        ctMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctMarcaActionPerformed(evt);
            }
        });

        lbManga.setText("Informe o tipo de manga (CURTA, LONGA):");

        lbEstampa.setText("Informe a estampa (LOGO DA MARCA, LISA, DESENHO):");

        lbMaterial.setText("Informe o tipo de material (ALGODAO, JEANS):");

        lbCuidados.setText("Informe os cuidados do material (lavar a mao, lavar na maquina):");

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        tbCamisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tamanho", "Cor", "Marca", "Manga", "Estampa", "Material", "Cuidados"
            }
        ));
        tblCamisa.setViewportView(tbCamisa);

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(btRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbCor, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ctCor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ctTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbManga, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ctManga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbMarca)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ctMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ctEstampa)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lbCuidados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ctMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ctCuidados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tblCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTamanho)
                    .addComponent(ctTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCor)
                    .addComponent(ctCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMarca)
                    .addComponent(ctMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbManga)
                    .addComponent(ctManga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstampa)
                    .addComponent(ctEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaterial)
                    .addComponent(ctMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCuidados)
                    .addComponent(ctCuidados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btSair)
                    .addComponent(btLimpar)
                    .addComponent(btConsultar)
                    .addComponent(btAlterar)
                    .addComponent(btRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tblCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctTamanhoActionPerformed

    private void ctCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctCorActionPerformed

    private void ctMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctMarcaActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadastrarCamisa();
        listarTab();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultarCamisa();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterarCamisa();
        listarTab();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        remover();
        listarTab();
    }//GEN-LAST:event_btRemoverActionPerformed

public void remover(){
    Camisa camisaConsulta = new Camisa();
    
    // Definindo os atributos da camisa com base nos campos de texto
    try {
        camisaConsulta.setTamanho(ctTamanho.getText());
    } catch (TamanhoErradoException tee) {
        tee.impTamanhoErrado();
        return;
    }
    
    try {
        camisaConsulta.setCor(ctCor.getText());
    } catch (CorErradaException cee) {
        cee.impCorErrada();
        return;
    }
    
    try {
        camisaConsulta.setMarca(ctMarca.getText());
    } catch (MarcaErradaException mee) {
        mee.impMarcaErrada();
        return;
    }
    
    try {
        camisaConsulta.setTipoManga(ctManga.getText());
    } catch (MangaErradaException mee) {
        mee.impMangaErrada();
        return;
    }
    
    try {
        camisaConsulta.setEstampa(ctEstampa.getText());
    } catch (EstampaErradaException eee) {
        eee.impEstampaErrada();
        return;
    }
    
    try {
        camisaConsulta.getMaterial().setTipo(ctMaterial.getText());
    } catch (TipoErradoException tee) {
        tee.impTipoErrado();
        return;
    }
    
    try {
        camisaConsulta.getMaterial().setCuidados(ctCuidados.getText());
    } catch(CuidadosErradosException cee) {
        cee.impCuidadosErrados();
        return;
    }
    
    
    
    
    
    
    if (camisaConsulta != null) {
        ctTamanho.setText(camisaConsulta.getTamanho());
        ctCor.setText(camisaConsulta.getCor());
        ctMarca.setText(camisaConsulta.getMarca());
        ctManga.setText(camisaConsulta.getTipoManga());
        ctEstampa.setText(camisaConsulta.getEstampa());
        int x = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir essa Camisa?", "Confirmacao de exclusao",JOptionPane.YES_NO_CANCEL_OPTION);
        if(x == 0){
            estoque.removeCamisa(camisaConsulta);
            JOptionPane.showMessageDialog(null, "Camisa excluida com sucesso", "Exclusao de Camisa", 1);
        limpar();
        }
    } else {
        JOptionPane.showMessageDialog(null, "Nao existe Camisa com esses dados", "", JOptionPane.YES_NO_CANCEL_OPTION);
        limpar();
    }
}
   
    
public void alterarCamisa(){
    Camisa camisaConsulta = new Camisa();
    
    // Definindo os atributos da camisa com base nos campos de texto
        
    try {
        camisaConsulta.setTamanho(ctTamanho.getText());
    } catch (TamanhoErradoException tee) {
        tee.impTamanhoErrado();
        return;
    }
    
    try {
        camisaConsulta.setCor(ctCor.getText());
    } catch (CorErradaException cee) {
        cee.impCorErrada();
        return;
    }
    
    try {
        camisaConsulta.setMarca(ctMarca.getText());
    } catch (MarcaErradaException mee) {
        mee.impMarcaErrada();
        return;
    }
    
    try {
        camisaConsulta.setTipoManga(ctManga.getText());
    } catch (MangaErradaException mee) {
        mee.impMangaErrada();
        return;
    }
    
    try {
        camisaConsulta.setEstampa(ctEstampa.getText());
    } catch (EstampaErradaException eee) {
        eee.impEstampaErrada();
        return;
    }
    
    try {
        camisaConsulta.getMaterial().setTipo(ctMaterial.getText());
    } catch (TipoErradoException tee) {
        tee.impTipoErrado();
        return;
    }
    
    try {
        camisaConsulta.getMaterial().setCuidados(ctCuidados.getText());
    } catch(CuidadosErradosException cee) {
        cee.impCuidadosErrados();
        return;
    }
    
    
    
    Camisa camisaAtualizada = estoque.atualizaCamisa(camisaConsulta);
    
    
    if (camisaAtualizada != null) {
        ctTamanho.setText(camisaAtualizada.getTamanho());
        ctCor.setText(camisaAtualizada.getCor());
        ctMarca.setText(camisaAtualizada.getMarca());
        ctManga.setText(camisaAtualizada.getTipoManga());
        ctEstampa.setText(camisaAtualizada.getEstampa());
        JOptionPane.showMessageDialog(null, "Dados da Camisa atualizados com sucesso!", "Atulização da Camisa",1);
    } else {
        JOptionPane.showMessageDialog(null, "Nao existe Camisa com esses dados", "Camisa inexistente", JOptionPane.ERROR_MESSAGE);
        
    }
}
    
public void listarTab(){
        DefaultTableModel modelo = (DefaultTableModel) tbCamisa.getModel();
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Camisa camisa : estoque.getBdCamisa()){
            modelo.insertRow(posLin, new Object []{camisa.getTamanho(),
                                                   camisa.getCor(),
                                                   camisa.getMarca(),
                                                   camisa.getTipoManga(),
                                                   camisa.getEstampa(), 
                                                   camisa.getMaterial().getTipo(), 
                                                   camisa.getMaterial().getCuidados()});
            posLin++;
        }
    }    

public void consultarCamisa() {
    Camisa camisaConsulta = new Camisa();
    
    // Definindo os atributos da camisa com base nos campos de texto
    try {
        camisaConsulta.setTamanho(ctTamanho.getText());
    } catch (TamanhoErradoException tee) {
        tee.impTamanhoErrado();
        return;
    }
    
    try {
        camisaConsulta.setCor(ctCor.getText());
    } catch (CorErradaException cee) {
        cee.impCorErrada();
        return;
    }
    
    try {
        camisaConsulta.setMarca(ctMarca.getText());
    } catch (MarcaErradaException mee) {
        mee.impMarcaErrada();
        return;
    }
    
    try {
        camisaConsulta.setTipoManga(ctManga.getText());
    } catch (MangaErradaException mee) {
        mee.impMangaErrada();
        return;
    }
    
    try {
        camisaConsulta.setEstampa(ctEstampa.getText());
    } catch (EstampaErradaException eee) {
        eee.impEstampaErrada();
        return;
    }
    
    try {
        camisaConsulta.getMaterial().setTipo(ctMaterial.getText());
    } catch (TipoErradoException tee) {
        tee.impTipoErrado();
        return;
    }
    
    try {
        camisaConsulta.getMaterial().setCuidados(ctCuidados.getText());
    } catch(CuidadosErradosException cee) {
        cee.impCuidadosErrados();
        return;
    }
    
    
    camisaConsulta = estoque.consCamisa(camisaConsulta);
    
    
    if (camisaConsulta != null) {
        ctTamanho.setText(camisaConsulta.getTamanho());
        ctCor.setText(camisaConsulta.getCor());
        ctMarca.setText(camisaConsulta.getMarca());
        ctManga.setText(camisaConsulta.getTipoManga());
        ctEstampa.setText(camisaConsulta.getEstampa());
        JOptionPane.showMessageDialog(null, "Confirme os dados da Camisa", "Confirmacao de dados",1);
    } else {
        JOptionPane.showMessageDialog(null, "Nao existe Camisa com esses dados", "Camisa inexistente", JOptionPane.ERROR_MESSAGE);
        limpar();
    }
}


    public void cadastrarCamisa(){
        camisa = new Camisa();
        
        try{
        try{
        camisa.setTamanho(ctTamanho.getText());
        }catch(TamanhoErradoException tee){
            tee.impTamanhoErrado();
            ctTamanho.setText("");
            ctTamanho.requestFocus();
            return;
        }
        
        try{
        camisa.setCor(ctCor.getText());
        }catch(CorErradaException cee){
            cee.impCorErrada();
            ctCor.setText("");
            ctCor.requestFocus();
            return;
        }
        
        try{        
        camisa.setMarca(ctMarca.getText());
        }catch(MarcaErradaException mee){
            mee.impMarcaErrada();
            ctMarca.setText("");
            ctMarca.requestFocus();
            return;
        }
        
        try{            
        camisa.setTipoManga(ctManga.getText());
        }catch(MangaErradaException mee){
            mee.impMangaErrada();
            ctManga.setText("");
            ctManga.requestFocus();
            return;
        }
        
        try{
        camisa.setEstampa(ctEstampa.getText());
        }catch(EstampaErradaException eee){
            eee.impEstampaErrada();
            ctEstampa.setText("");
            ctEstampa.requestFocus();
            return;
        }
        try{
        camisa.getMaterial().setTipo(ctMaterial.getText());
        } catch(TipoErradoException tee){
            tee.impTipoErrado();
            ctMaterial.setText("");
            ctMaterial.requestFocus();
            return;
        }
        try{    
        camisa.getMaterial().setCuidados(ctCuidados.getText());
        }catch(CuidadosErradosException cee){
            cee.impCuidadosErrados();
            ctCuidados.setText("");
            ctCuidados.requestFocus();
            return;
        }
        camisa = estoque.cadCamisa(camisa);
        if(camisa != null){
            JOptionPane.showMessageDialog(null,"Camisa cadastrada com sucesso!", "Cadastro OK", 1);
            limpar();
        }

        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro ao cadastrar a camisa!", "Cadastro ERRO", 0);
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja Fechar o cadastro de camisa?", "Saida", JOptionPane.YES_NO_OPTION);
            if(resp == 0){
                this.dispose();
            }
        }
    
    public void limpar(){
        ctTamanho.setText("");
        ctCor.setText("");
        ctMarca.setText("");
        ctManga.setText("");
        ctEstampa.setText("");
        ctMaterial.setText("");
        ctCuidados.setText("");
        ctTamanho.requestFocus();  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarCamisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarCamisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarCamisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarCamisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastrarCamisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField ctCor;
    private javax.swing.JTextField ctCuidados;
    private javax.swing.JTextField ctEstampa;
    private javax.swing.JTextField ctManga;
    private javax.swing.JTextField ctMarca;
    private javax.swing.JTextField ctMaterial;
    private javax.swing.JTextField ctTamanho;
    private javax.swing.JLabel lbCor;
    private javax.swing.JLabel lbCuidados;
    private javax.swing.JLabel lbEstampa;
    private javax.swing.JLabel lbManga;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbMaterial;
    private javax.swing.JLabel lbTamanho;
    private javax.swing.JTable tbCamisa;
    private javax.swing.JScrollPane tblCamisa;
    // End of variables declaration//GEN-END:variables
}
