//Nome: Rafael Tomé da Silva - RA:2623412;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rafae
 */
public class FormCadastrarCalca extends javax.swing.JFrame {

    private Calca calca;
    private Estoque estoque = new Estoque();
    
    private static FormCadastrarCalca cadCalUnico;
    
    public FormCadastrarCalca() {
        initComponents();
        listarTab();
    }
    
    // MÉTODO SINGLETON
    public static FormCadastrarCalca getCadastrarCalca(){
        if(cadCalUnico == null){
        cadCalUnico = new FormCadastrarCalca();
        }
        return cadCalUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCor = new javax.swing.JLabel();
        ctCuidados = new javax.swing.JTextField();
        ctCor = new javax.swing.JTextField();
        lbMarca = new javax.swing.JLabel();
        ctMarca = new javax.swing.JTextField();
        lbCintura = new javax.swing.JLabel();
        ctCintura = new javax.swing.JTextField();
        lbComprimento = new javax.swing.JLabel();
        ctComprimento = new javax.swing.JTextField();
        lbTamanho = new javax.swing.JLabel();
        lbMaterial = new javax.swing.JLabel();
        ctTamanho = new javax.swing.JTextField();
        ctMaterial = new javax.swing.JTextField();
        lbCuidados = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        tblCamisa = new javax.swing.JScrollPane();
        tbCamisa = new javax.swing.JTable();
        btLimpar1 = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Calca");
        setAlwaysOnTop(true);

        lbCor.setText("Informe a cor (branca, preta, azul):");

        ctCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctCorActionPerformed(evt);
            }
        });

        lbMarca.setText("Informe a marca (BAW, SUFGANG, APPROVE, WATS, HIGH):");

        ctMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctMarcaActionPerformed(evt);
            }
        });

        lbCintura.setText("Informe a cintura (ALTA, MEDIA, BAIXA):");

        lbComprimento.setText("Informe o comprimento (96-98, 98-100, 100-102, 102-104, 104-106):");

        lbTamanho.setText("Informe o tamanho (PP, P, M, G, GG):");

        lbMaterial.setText("Informe o tipo de material (ALGODAO, JEANS):");

        ctTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctTamanhoActionPerformed(evt);
            }
        });

        lbCuidados.setText("Informe os cuidados do material (lavar a mao, lavar na maquina):");

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        tbCamisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tamanho", "Cor", "Marca", "Cintura", "Comprimento", "Material", "Cuidados"
            }
        ));
        tblCamisa.setViewportView(tbCamisa);

        btLimpar1.setText("Limpar");
        btLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpar1ActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbComprimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btConsultar)
                        .addGap(22, 22, 22)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btRemover)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar1)
                        .addGap(34, 34, 34)
                        .addComponent(btSair)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCor, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctCor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCintura, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctCintura, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ctMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbCuidados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ctMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctCuidados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tblCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTamanho)
                    .addComponent(ctTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCor)
                    .addComponent(ctCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMarca)
                    .addComponent(ctMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCintura)
                    .addComponent(ctCintura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComprimento)
                    .addComponent(ctComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaterial)
                    .addComponent(ctMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCuidados)
                    .addComponent(ctCuidados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btSair)
                    .addComponent(btLimpar1)
                    .addComponent(btConsultar)
                    .addComponent(btAlterar)
                    .addComponent(btRemover))
                .addGap(18, 18, 18)
                .addComponent(tblCamisa, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctCorActionPerformed

    private void ctMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctMarcaActionPerformed

    private void ctTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctTamanhoActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadastrarCalca();
        listarTab();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpar1ActionPerformed
        limpar();
    }//GEN-LAST:event_btLimpar1ActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultarCalca();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterarCalca();
        listarTab();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        remover();
        listarTab();
    }//GEN-LAST:event_btRemoverActionPerformed

    public void remover(){
    Calca calcaConsulta = new Calca();
    
    // Definindo os atributos da camisa com base nos campos de texto
    try {
        calcaConsulta.setTamanho(ctTamanho.getText());
    } catch (TamanhoErradoException tee) {
        tee.impTamanhoErrado();
        return;
    }
    
    try {
        calcaConsulta.setCor(ctCor.getText());
    } catch (CorErradaException cee) {
        cee.impCorErrada();
        return;
    }
    
    try {
        calcaConsulta.setMarca(ctMarca.getText());
    } catch (MarcaErradaException mee) {
        mee.impMarcaErrada();
        return;
    }
    
    try {
        calcaConsulta.setTipoCintura(ctCintura.getText());
    } catch (CinturaErradaException mee) {
        mee.impCinturaErrada();
        return;
    }
    
    try {
        calcaConsulta.setComprimento(ctComprimento.getText());
    } catch (ComprimentoErradoException eee) {
        eee.impComprimentoErrado();
        return;
    }
    
    try {
        calcaConsulta.getMaterial().setTipo(ctMaterial.getText());
    } catch (TipoErradoException tee) {
        tee.impTipoErrado();
        return;
    }
    
    try {
        calcaConsulta.getMaterial().setCuidados(ctCuidados.getText());
    } catch(CuidadosErradosException cee) {
        cee.impCuidadosErrados();
        return;
    }
    
    
    
    
    
    
    if (calcaConsulta != null) {
        ctTamanho.setText(calcaConsulta.getTamanho());
        ctCor.setText(calcaConsulta.getCor());
        ctMarca.setText(calcaConsulta.getMarca());
        ctCintura.setText(calcaConsulta.getTipoCintura());
        ctComprimento.setText(calcaConsulta.getComprimento());
        int x = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir essa Calca?", "Confirmacao de exclusao",JOptionPane.YES_NO_CANCEL_OPTION);
        if(x == 0){
            estoque.removeCalca(calcaConsulta);
            JOptionPane.showMessageDialog(null, "Calca excluida com sucesso", "Exclusao de Calca", 1);
        limpar();
        }
    } else {
        JOptionPane.showMessageDialog(null, "Nao existe Calca com esses dados", "", JOptionPane.YES_NO_CANCEL_OPTION);
        limpar();
    }
}
    
    public void alterarCalca() {
    Calca calcaConsulta = new Calca();
    
    // Definindo os atributos da calca com base nos campos de texto
    try {
        calcaConsulta.setTamanho(ctTamanho.getText());
    } catch (TamanhoErradoException tee) {
        tee.impTamanhoErrado();
        return;
    }
    
    try {
        calcaConsulta.setCor(ctCor.getText());
    } catch (CorErradaException cee) {
        cee.impCorErrada();
        return;
    }
    
    try {
        calcaConsulta.setMarca(ctMarca.getText());
    } catch (MarcaErradaException mee) {
        mee.impMarcaErrada();
        return;
    }
    
    try {
        calcaConsulta.setTipoCintura(ctCintura.getText());
    } catch (CinturaErradaException mee) {
        mee.impCinturaErrada();
        return;
    }
    
    try {
        calcaConsulta.setComprimento(ctComprimento.getText());
    } catch (ComprimentoErradoException eee) {
        eee.impComprimentoErrado();
        return;
    }
    
    try {
        calcaConsulta.getMaterial().setTipo(ctMaterial.getText());
    } catch (TipoErradoException tee) {
        tee.impTipoErrado();
        return;
    }
    
    try {
        calcaConsulta.getMaterial().setCuidados(ctCuidados.getText());
    } catch(CuidadosErradosException cee) {
        cee.impCuidadosErrados();
        return;
    }
    
    
    calcaConsulta = estoque.atualizaCalca(calcaConsulta);
    
    
    if (calcaConsulta != null) {
        ctTamanho.setText(calcaConsulta.getTamanho());
        ctCor.setText(calcaConsulta.getCor());
        ctMarca.setText(calcaConsulta.getMarca());
        ctCintura.setText(calcaConsulta.getTipoCintura());
        ctComprimento.setText(calcaConsulta.getComprimento());
        JOptionPane.showMessageDialog(null, "Confirme os dados da Calca atualizados", "Confirmacao de dados atualizados",1);
    } else {
        JOptionPane.showMessageDialog(null, "Nao existe Calca com esses dados", "Calca inexistente", JOptionPane.ERROR_MESSAGE);
        limpar();
    }
}
    
    public void consultarCalca() {
    Calca calcaConsulta = new Calca();
    
    // Definindo os atributos da calca com base nos campos de texto
    try {
        calcaConsulta.setTamanho(ctTamanho.getText());
    } catch (TamanhoErradoException tee) {
        tee.impTamanhoErrado();
        return;
    }
    
    try {
        calcaConsulta.setCor(ctCor.getText());
    } catch (CorErradaException cee) {
        cee.impCorErrada();
        return;
    }
    
    try {
        calcaConsulta.setMarca(ctMarca.getText());
    } catch (MarcaErradaException mee) {
        mee.impMarcaErrada();
        return;
    }
    
    try {
        calcaConsulta.setTipoCintura(ctCintura.getText());
    } catch (CinturaErradaException mee) {
        mee.impCinturaErrada();
        return;
    }
    
    try {
        calcaConsulta.setComprimento(ctComprimento.getText());
    } catch (ComprimentoErradoException eee) {
        eee.impComprimentoErrado();
        return;
    }
    
    try {
        calcaConsulta.getMaterial().setTipo(ctMaterial.getText());
    } catch (TipoErradoException tee) {
        tee.impTipoErrado();
        return;
    }
    
    try {
        calcaConsulta.getMaterial().setCuidados(ctCuidados.getText());
    } catch(CuidadosErradosException cee) {
        cee.impCuidadosErrados();
        return;
    }
    
    
    calcaConsulta = estoque.consCalca(calcaConsulta);
    
    
    if (calcaConsulta != null) {
        ctTamanho.setText(calcaConsulta.getTamanho());
        ctCor.setText(calcaConsulta.getCor());
        ctMarca.setText(calcaConsulta.getMarca());
        ctCintura.setText(calcaConsulta.getTipoCintura());
        ctComprimento.setText(calcaConsulta.getComprimento());
        JOptionPane.showMessageDialog(null, "Confirme os dados da Calca", "Confirmacao de dados",1);
    } else {
        JOptionPane.showMessageDialog(null, "Nao existe Calca com esses dados", "Calca inexistente", JOptionPane.ERROR_MESSAGE);
        limpar();
    }
}
    
    public void limpar(){
        ctTamanho.setText("");
        ctCor.setText("");
        ctMarca.setText("");
        ctCintura.setText("");
        ctComprimento.setText("");
        ctMaterial.setText("");
        ctCuidados.setText("");
        ctTamanho.requestFocus();  
    }
    
    public void listarTab(){
        DefaultTableModel modelo = (DefaultTableModel) tbCamisa.getModel();
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Calca calca : estoque.getBdCalca()){
            modelo.insertRow(posLin, new Object []{calca.getTamanho(),
                                                   calca.getCor(),
                                                   calca.getMarca(),
                                                   calca.getTipoCintura(),
                                                   calca.getComprimento(), 
                                                   calca.getMaterial().getTipo(), 
                                                   calca.getMaterial().getCuidados()});
            posLin++;
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja Fechar o cadastro de Calca?", "Saida", JOptionPane.YES_NO_OPTION);
            if(resp == 0){
                this.dispose();
            }
        }    
    
    public void cadastrarCalca(){
        calca = new Calca();
        
        
        try{
        calca.setTamanho(ctTamanho.getText());
        }catch(TamanhoErradoException tee){
            tee.impTamanhoErrado();
            ctTamanho.setText("");
            ctTamanho.requestFocus();
            return;
        }
        
        try{
        calca.setCor(ctCor.getText());
        }catch(CorErradaException cee){
            cee.impCorErrada();
            ctCor.setText("");
            ctCor.requestFocus();
            return;
        }
        
        try{        
        calca.setMarca(ctMarca.getText());
        }catch(MarcaErradaException mee){
            mee.impMarcaErrada();
            ctMarca.setText("");
            ctMarca.requestFocus();
            return;
        }
        
        try{            
        calca.setTipoCintura(ctCintura.getText());
        }catch(CinturaErradaException mee){
            mee.impCinturaErrada();
            ctCintura.setText("");
            ctCintura.requestFocus();
            return;
        }
        
        try{
        calca.setComprimento(ctComprimento.getText());
        }catch(ComprimentoErradoException eee){
            eee.impComprimentoErrado();
            ctComprimento.setText("");
            ctComprimento.requestFocus();
            return;
        }
        try{
        calca.getMaterial().setTipo(ctMaterial.getText());
        } catch(TipoErradoException tee){
            tee.impTipoErrado();
            ctMaterial.setText("");
            ctMaterial.requestFocus();
            return;
        }
        try{    
        calca.getMaterial().setCuidados(ctCuidados.getText());
        }catch(CuidadosErradosException cee){
            cee.impCuidadosErrados();
            ctCuidados.setText("");
            ctCuidados.requestFocus();
            return;
        }
        calca = estoque.cadCalca(calca);
        if(calca != null){
            JOptionPane.showMessageDialog(null,"Calca cadastrada com sucesso!", "Cadastro OK", 1);
            limpar();
        }

        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarCalca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarCalca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarCalca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarCalca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastrarCalca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar1;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField ctCintura;
    private javax.swing.JTextField ctComprimento;
    private javax.swing.JTextField ctCor;
    private javax.swing.JTextField ctCuidados;
    private javax.swing.JTextField ctMarca;
    private javax.swing.JTextField ctMaterial;
    private javax.swing.JTextField ctTamanho;
    private javax.swing.JLabel lbCintura;
    private javax.swing.JLabel lbComprimento;
    private javax.swing.JLabel lbCor;
    private javax.swing.JLabel lbCuidados;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbMaterial;
    private javax.swing.JLabel lbTamanho;
    private javax.swing.JTable tbCamisa;
    private javax.swing.JScrollPane tblCamisa;
    // End of variables declaration//GEN-END:variables
}
